[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "shrek"
description = "biblioteca que troca os valores por personagens aleatorios de shrek"
version = "0.1.0"
dependencies = []